<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="24" total="26" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-26T08:17:51 IST" name="Suite" finished-at="2022-04-26T08:17:51 IST" duration-ms="45">
    <groups>
    </groups>
    <test started-at="2022-04-26T08:17:51 IST" name="TestCase002" finished-at="2022-04-26T08:17:51 IST" duration-ms="45">
      <class name="testNGDemo.AssertionDemo">
        <test-method signature="testMethod2()[pri:0, instance:testNGDemo.AssertionDemo@26e356f0]" started-at="2022-04-26T08:17:51 IST" name="testMethod2" finished-at="2022-04-26T08:17:51 IST" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at testNGDemo.AssertionDemo.testMethod2(AssertionDemo.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
      </class> <!-- testNGDemo.AssertionDemo -->
    </test> <!-- TestCase002 -->
    <test started-at="2022-04-26T08:17:51 IST" name="TestCase001" finished-at="2022-04-26T08:17:51 IST" duration-ms="45">
      <class name="testNGDemo.AssertionDemo">
        <test-method signature="testMethod1()[pri:0, instance:testNGDemo.AssertionDemo@3bf9ce3e]" started-at="2022-04-26T08:17:51 IST" name="testMethod1" finished-at="2022-04-26T08:17:51 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
      </class> <!-- testNGDemo.AssertionDemo -->
    </test> <!-- TestCase001 -->
  </suite> <!-- Suite -->
</testng-results>
